### ISSUE TITLE
Multisig address changes with change of order

### ISSUE THREAD

**Issue by shayanb** [richardkiss/pycoin#95] opened 2015-03-02 16:36 UTC
I use this to generate multisig address from N addresses (N=2 in this scenario).
```
def generate_multisig_address(keys, N=2, M=2):
    from pycoin.tx.pay_to import address_for_pay_to_script
    underlying_script = ScriptMultisig(n=N, sec_keys=[key["key_pair_as_sec"] for key in keys[:M]]).script()
    address = address_for_pay_to_script(underlying_script) #is it possible to get redeemScript?
    return address
```

However if we change the order of the keys, it will generate different address:
```
[u'159F7ik2d5emNovLjHgo4A6J9VD3UhZ9gg', u'1B7dPQkjxoFtzoZ4wSnhN3TTVg5Xtiwm8W']
Multisig address: 3MvymRh5nnvqs7vVHivzNBVV5hE9R8FGyt

[u'1B7dPQkjxoFtzoZ4wSnhN3TTVg5Xtiwm8W', u'159F7ik2d5emNovLjHgo4A6J9VD3UhZ9gg']
Multisig address: 3NqzcdAnkQ69wB2d98nJ66AGq3EQEHawyJ
```

**Comment by richardkiss** [comment] 2015-03-02 20:18
This is the expected behaviour. Is there a standard for ordering the addresses? (Lexigraphically, for example?) I would expect the order to be settable by the user so, for example, the "bank's" address always goes second and the "client's" address always goes first.

**Comment by mbogosian** [comment] 2015-03-02 20:55
I might have misunderstood, but I *think* changing the order *should* change the P2SH address. Order is important in a multisig script (hence #93, which says that `is_signature_ok(...)` *should* fail if the signatures appear in the wrong order; the bug was that it was returning `True` under those circumstances). But perhaps I have misunderstood this issue?

**Comment by shayanb** [comment] 2015-03-02 22:42
I usually try out the bitcore playground to see if other implementations behave the same way or not and on this case, even if I replace the addresses (2 of 2) with each other the resulting multisig address will stay the same: http://bitcore.io/playground/#/multisig

in the case of pycoin implementation, is it possible to sign transactions from all multisig addresses? or only one of the possible addresses would be valid? I guess this should be either mentioned somewhere or be fixed to only generate same address if the [addresses] are the same but in different order.

**Comment by shayanb** [comment] 2015-03-03 15:44
Actually I just checked and bitcore.io do sort the public keys, and that is why it results in same multisig address.
So maybe just mentioning this in the function definition or any documentations suffice.
https://github.com/bitpay/bitcore/blob/master/lib/script/script.js#L538
```
/**
 * @returns {Script} a new Multisig output script for given public keys,
 * requiring m of those public keys to spend
 * @param {PublicKey[]} publicKeys - list of all public keys controlling the output
 * @param {number} threshold - amount of required signatures to spend the output
 * @param {Object=} opts - Several options:
 *        - noSorting: defaults to false, if true, don't sort the given
 *                      public keys before creating the script
 */
Script.buildMultisigOut = function(publicKeys, threshold, opts) {
  $.checkArgument(threshold <= publicKeys.length,
                  'Number of required signatures must be less than or equal to the number of public keys');
  opts = opts || {};
  var script = new Script();
  script.add(Opcode.smallInt(threshold));
  publicKeys = _.map(publicKeys, PublicKey);
  var sorted = publicKeys;
  if (!opts.noSorting) {
    sorted = _.sortBy(publicKeys, function(publicKey) {
      return publicKey.toString('hex');
    });
  }
  for (var i = 0; i < sorted.length; i++) {
    var publicKey = sorted[i];
    script.add(publicKey.toBuffer());
  }
  script.add(Opcode.smallInt(publicKeys.length));
  script.add(Opcode.OP_CHECKMULTISIG);
  return script;
};
```

**Comment by mbogosian** [comment] 2015-03-07 22:26
My guess is that's a bug in bitcore.io. The Bitcoin VM won't validate signatures out of order (at least not one that's written according to the specification). From https://bitcoin.org/en/developer-reference#term-op-checkmultisig:

>:warning:  **[`OP_CHECKMULTISIG`](https://bitcoin.org/en/developer-reference#term-op-checkmultisig) warning**: The multisig verification process described above requires that signatures in the signature script be provided in the same order as their corresponding public keys in the pubkey script or redeem script. For example, the following combined signature and pubkey script will produce the stack and comparisons shown:
>```
OP_0 <A sig> <B sig> OP_2 <A pubkey> <B pubkey> <C pubkey> OP_3

Sig Stack       Pubkey Stack  (Actually a single stack)
---------       ------------
B sig           C pubkey
A sig           B pubkey
OP_0            A pubkey

1. B sig compared to C pubkey (no match)
2. B sig compared to B pubkey (match #1)
3. A sig compared to A pubkey (match #2)

Success: two matches found
```
>
>But reversing the order of the signatures with everything else the same will fail, as shown below:
>
>```
OP_0 <B sig> <A sig> OP_2 <A pubkey> <B pubkey> <C pubkey> OP_3

Sig Stack       Pubkey Stack  (Actually a single stack)
---------       ------------
A sig           C pubkey
B sig           B pubkey
OP_0            A pubkey

1. A sig compared to C pubkey (no match)
2. A sig compared to B pubkey (no match)

Failure, aborted: two signature matches required but none found so
                  far, and there's only one pubkey remaining
```

**Comment by richardkiss** [comment] 2015-11-18 18:00
Closing because I don't think this is a bug in pycoin.

**Closed by richardkiss** 2015-11-18 18:00 UTC

**Comment by derrend** [comment] 2015-11-19 10:52
Just for my sanity could someone please let me know if there are any problems or gotchas with the below script?

It's modeled on the OP example but I stripped out a few components which didn't seem to serve a purpose such as the `M` variable.

Thanks.

    from pycoin.tx.pay_to import ScriptMultisig
    from pycoin.tx.pay_to import address_for_pay_to_script
    from pycoin.key import Key

    k1 = Key.from_text('xpub661MyMwAqRbcGDkZfNsdrJMf2QSCiUSeLXfJvFfLo4mkPsQXLmeqmE8soxP39ukevmZ3azjMrhhf6uSCLUsLJTDrgdxLxZMeQ5X96xtQTno')
    k2 = Key.from_text('xpub661MyMwAqRbcFY3yGMuLFXTJvRViVJukKPUTScPJoXwgf9sHfHy6WnGcGm4R7LFG3XjDnqC5MQGkHEXJ3fFqMtmSf4jfVEhnnCJqiw3ow7e')
    keys = (k1,k2)

    def generate_multisig_address(keys, N=2):
        redeem_script = ScriptMultisig(n=N, sec_keys=[key.sec() for key in keys]).script()
        return address_for_pay_to_script(redeem_script)

    generate_multisig_address(keys, N=2)

**Comment by richardkiss** [comment] 2015-12-07 18:37
This seems okay. You might also look at the tests of this function here https://github.com/richardkiss/pycoin/blob/master/tests/pay_to_test.py#L163

**Comment by derrend** [comment] 2015-12-07 21:30
Great stuff, thank you :)
