### ISSUE TITLE
Pycoin does not validate Gavin Andresen's test multisig transaction.

### ISSUE THREAD

**Issue by gitmarek** [richardkiss/pycoin#71] opened 2015-01-05 23:16 UTC
This is related to the error exposed in the commit: ec69967

I tried to check the signature of Gavin Andresen's test multisig transaction:
837dea37ddc8b1e3ce646f1a656e79bbd8cc7f558ac56a169626d649ebe2a3ba
described in his gist: https://gist.github.com/gavinandresen/3966071
but the function is_signature_ok() returns False.

Then I tried to sign a raw transaction Gavin created myself, and the result
does have a valid (according to pycoin) signature, however a different one.
You can check this running the following code:
https://gist.github.com/gitmarek/3593fbd9eecbbbebcdc0

Two questions:
1. How could I sign the raw transaction one private key at the time, as in the Gavin's gist?
When I try to specify only one key in hash160_lookup dict, I got an error.
2. Is the whole issue a bug in pycoin, or am I doing something wrong?

**Comment by richardkiss** [comment] 2015-01-07 05:23
There is a method in pycoin/services/bitcoind.py called "bitcoind_agrees_on_transaction_validity" that is useful for checking agreement of bitcoind and pycoin that you might find useful.

There is a bug in pycoin that causes some (but not all) multisig transactions to not validate when they should. I have a test case which currently fails, so I just need to track down what's wrong. I think it's a problem in my implementation of OP_CHECKMULTISIG.

You should be able to partially sign with just one key. I seem to remember that I have a test case that does this...

**Comment by gitmarek** [comment] 2015-01-07 22:32
That test case is in tests/pay_to_test.py, in test_multisig_one_at_a_time().
Looks like a great starting point to learn pycoin tx internals, thanks. I shall rewrite my gist as test case,
checking if Gavin's transaction signature is ok and than trying to recreate it from scratch.

That problem in the implementation of OP_CHECKMULTISIG, do you think it is in 
tx/script/vm.py, or deeper in ecdsa.possible_public_pairs_for_signature()?  In other words,
do you think eval_script() reads bad data from script and feeds it into possible_public_pairs_for_signature() or the signature_hash and sig_pair are correct?

**Comment by richardkiss** [comment] 2015-01-08 19:23
My gut feeling is that the problem is possible_public_pairs_for_signature. A prior implementation of OP_CHECKMULTISIG did the naïve thing of trying every signature with every public pair... that one probably worked (although it predated the test that now fails).

**Comment by gitmarek** [comment] 2015-01-08 21:19
I changed the implementation of OP_CHECKMULTISIG to the earlier version
and unfortunately the tx_test.py still fails at the same point.
(You can see what code I actually run the test against at 9e519b4)

**Comment by gitmarek** [comment] 2015-01-12 23:43
The transaction couldn't be validated because signature_hash in vm.py:check_signature() is wrong!
If I put the correct signature_hash, the transaction validates.
Please, checkout: c695b79, and run tests/ga_multisig_test.py.

**Comment by gitmarek** [comment] 2015-01-13 12:49
I came up with the solution: PR #73.
What do you think?

**Comment by gitmarek** [comment] 2015-01-14 16:11
Unfortunately, now pay_to_test.py fails.
I think that's because Tx.sign_tx_in() does not handle P2SH input correctly.  I took care of it in 6a365a8

**Comment by ysobolev** [comment] 2015-01-24 22:47
@gitmarek I can confirm your fix works. Pycoin now correctly signs multisig transactions.

**Comment by richardkiss** [comment] 2015-02-01 04:31
Merged (squashed) in 93334719719a6f11144425030594250432b33840

**Closed by richardkiss** 2015-02-01 04:31 UTC
